name: Test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Display environment variables
      run: |
        echo "VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}"
        echo "VITE_BASE: ${{ vars.VITE_BASE }}"
    - name: Display environment variables
      run: |
        echo "VITE_API_BASE_URL: $VITE_API_BASE_URL"
        echo "VITE_BASE: $VITE_BASE"
      env:
        VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
        VITE_BASE: ${{ vars.VITE_BASE }}
    